[theme]
backgroundColor="#eee4d8"
secondaryBackgroundColor="#b28479"
primaryColor="#963615"
textColor="#f8f4f3"
font = "IBM Plex Serif:https://fonts.googleapis.com/css2?family=IBM+Plex+Serif&display=swap"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap"
